/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author giselle
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupO = new javax.swing.ButtonGroup();
        btnGroupC = new javax.swing.ButtonGroup();
        CajitaTexto = new javax.swing.JTextField();
        rdbtnB = new javax.swing.JRadioButton();
        rdbtnC = new javax.swing.JRadioButton();
        rdbtnT = new javax.swing.JRadioButton();
        cCientific = new javax.swing.JPanel();
        btnPorc = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnP2 = new javax.swing.JButton();
        btnP3 = new javax.swing.JButton();
        btnPY = new javax.swing.JButton();
        btnR2 = new javax.swing.JButton();
        btnLog10 = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnCosh = new javax.swing.JButton();
        btnTanh = new javax.swing.JButton();
        btnSinh = new javax.swing.JButton();
        cBasic = new javax.swing.JPanel();
        btnNum9 = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnInv = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnPuntito = new javax.swing.JButton();
        btnRes = new javax.swing.JButton();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        rdbtnON = new javax.swing.JRadioButton();
        rdbtnOFF = new javax.swing.JRadioButton();
        Etiquetita = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CajitaTexto.setFont(new java.awt.Font("AppleGothic", 0, 13)); // NOI18N
        CajitaTexto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        CajitaTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajitaTextoActionPerformed(evt);
            }
        });

        btnGroupC.add(rdbtnB);
        rdbtnB.setSelected(true);
        rdbtnB.setText("Básica");
        rdbtnB.setToolTipText("Mostrar calculadora básica");
        rdbtnB.setActionCommand("B");

        btnGroupC.add(rdbtnC);
        rdbtnC.setText("Científica");
        rdbtnC.setToolTipText("Mostrar calculadora científica");
        rdbtnC.setActionCommand("C");

        btnGroupC.add(rdbtnT);
        rdbtnT.setText("Teclado");
        rdbtnT.setToolTipText("Ingresar datos por medio del teclado");
        rdbtnT.setActionCommand("T");

        btnPorc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPorcentaje.png"))); // NOI18N
        btnPorc.setToolTipText("Porcentaje, o presione '%'");
        btnPorc.setActionCommand("%");

        btnPi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPi.png"))); // NOI18N
        btnPi.setToolTipText("Ingresar pi, , o presione '?'");
        btnPi.setActionCommand("pi");

        btnP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPot2.png"))); // NOI18N
        btnP2.setToolTipText("Elevar al cuadrado");
        btnP2.setActionCommand("^2");

        btnP3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPot3.png"))); // NOI18N
        btnP3.setToolTipText("Elevar al cubo, o presione '^'");
        btnP3.setActionCommand("^3");

        btnPY.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPotY.png"))); // NOI18N
        btnPY.setToolTipText("Elevar el valor mostrado a la potencia del siguiente valor ingresado, o presione '^'");
        btnPY.setActionCommand("^y");

        btnR2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconRaiz.png"))); // NOI18N
        btnR2.setToolTipText("Raíz cuadrada, o presione '!'");
        btnR2.setActionCommand("R2");

        btnLog10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconLog10.png"))); // NOI18N
        btnLog10.setToolTipText("Calcular el logaritmo en base 10 del valor ingresado");
        btnLog10.setActionCommand("log10");

        btnLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconLog.png"))); // NOI18N
        btnLog.setToolTipText("Calcular el logaritmo natural del valor ingresado");
        btnLog.setActionCommand("log");

        btnCos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconCos.png"))); // NOI18N
        btnCos.setToolTipText("Calcular coseno");
        btnCos.setActionCommand("cos");

        btnSin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconSin.png"))); // NOI18N
        btnSin.setToolTipText("Calcular seno");
        btnSin.setActionCommand("sin");

        btnTan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconTan.png"))); // NOI18N
        btnTan.setToolTipText("Calcular tangente");
        btnTan.setActionCommand("tan");

        btnCosh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconCosh.png"))); // NOI18N
        btnCosh.setToolTipText("Calcular coseno hiperbólico");
        btnCosh.setActionCommand("cosh");

        btnTanh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconTanh.png"))); // NOI18N
        btnTanh.setToolTipText("Calcular tangente hiperbólico");
        btnTanh.setActionCommand("tanh");

        btnSinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconSinh.png"))); // NOI18N
        btnSinh.setToolTipText("Calcular seno hiperbólico");
        btnSinh.setActionCommand("sinh");

        javax.swing.GroupLayout cCientificLayout = new javax.swing.GroupLayout(cCientific);
        cCientific.setLayout(cCientificLayout);
        cCientificLayout.setHorizontalGroup(
            cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cCientificLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cCientificLayout.createSequentialGroup()
                        .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(cCientificLayout.createSequentialGroup()
                                    .addComponent(btnPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(cCientificLayout.createSequentialGroup()
                                    .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGroup(cCientificLayout.createSequentialGroup()
                                    .addComponent(btnPY, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnR2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(cCientificLayout.createSequentialGroup()
                                .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cCientificLayout.createSequentialGroup()
                                .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(90, 90, 90))
                    .addGroup(cCientificLayout.createSequentialGroup()
                        .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(cCientificLayout.createSequentialGroup()
                                .addComponent(btnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(cCientificLayout.createSequentialGroup()
                                .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        cCientificLayout.setVerticalGroup(
            cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cCientificLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPorc, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnP2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnP3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPY, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnR2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLog10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCosh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cCientificLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTanh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnNum9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num9.png"))); // NOI18N
        btnNum9.setToolTipText("Número 9");
        btnNum9.setActionCommand("9");

        btnAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconAC.png"))); // NOI18N
        btnAC.setToolTipText("Borrar");
        btnAC.setActionCommand("AC");

        btnInv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconMasMenos.png"))); // NOI18N
        btnInv.setToolTipText("Negar el valor mostrado");
        btnInv.setActionCommand("+/-");

        btnNum7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num7.png"))); // NOI18N
        btnNum7.setToolTipText("Número 7");
        btnNum7.setActionCommand("7");

        btnNum8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num8.png"))); // NOI18N
        btnNum8.setToolTipText("Número 8");
        btnNum8.setActionCommand("8");

        btnNum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num1.png"))); // NOI18N
        btnNum1.setToolTipText("Número 1");
        btnNum1.setActionCommand("1");

        btnNum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num2.png"))); // NOI18N
        btnNum2.setToolTipText("Número 2");
        btnNum2.setActionCommand("2");

        btnNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num3.png"))); // NOI18N
        btnNum3.setToolTipText("Número 3");
        btnNum3.setActionCommand("3");

        btnNum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num4.png"))); // NOI18N
        btnNum4.setToolTipText("Número 4");
        btnNum4.setActionCommand("4");

        btnNum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num5.png"))); // NOI18N
        btnNum5.setToolTipText("Número 5");
        btnNum5.setActionCommand("5");

        btnNum0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num0.png"))); // NOI18N
        btnNum0.setToolTipText("Número 0");
        btnNum0.setActionCommand("0");

        btnNum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/num6.png"))); // NOI18N
        btnNum6.setToolTipText("Número 6");
        btnNum6.setActionCommand("6");

        btnPuntito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconPuntito.png"))); // NOI18N
        btnPuntito.setToolTipText("Punto decimal");
        btnPuntito.setActionCommand(".");

        btnRes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconResultado.png"))); // NOI18N
        btnRes.setToolTipText("Igualar");
        btnRes.setActionCommand("=");

        btnSuma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconSuma.png"))); // NOI18N
        btnSuma.setToolTipText("Sumar");
        btnSuma.setActionCommand("+");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconResta.png"))); // NOI18N
        btnResta.setToolTipText("Restar");
        btnResta.setActionCommand("-");

        btnMult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconMult.png"))); // NOI18N
        btnMult.setToolTipText("Multiplicar");
        btnMult.setActionCommand("*");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnDiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/iconDiv.png"))); // NOI18N
        btnDiv.setToolTipText("Dividir");
        btnDiv.setActionCommand("/");

        javax.swing.GroupLayout cBasicLayout = new javax.swing.GroupLayout(cBasic);
        cBasic.setLayout(cBasicLayout);
        cBasicLayout.setHorizontalGroup(
            cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cBasicLayout.createSequentialGroup()
                .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnInv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPuntito, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cBasicLayout.createSequentialGroup()
                                .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(cBasicLayout.createSequentialGroup()
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cBasicLayout.setVerticalGroup(
            cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cBasicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNum4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addComponent(btnSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResta, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cBasicLayout.createSequentialGroup()
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPuntito, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(cBasicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRes, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGroupO.add(rdbtnON);
        rdbtnON.setSelected(true);
        rdbtnON.setText("ON");
        rdbtnON.setToolTipText("Encender");

        btnGroupO.add(rdbtnOFF);
        rdbtnOFF.setText("OFF");
        rdbtnOFF.setToolTipText("Apagar");

        Etiquetita.setForeground(new java.awt.Color(255, 0, 51));
        Etiquetita.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnOFF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnB))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdbtnC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbtnT))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CajitaTexto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cBasic, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Etiquetita, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cCientific, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Etiquetita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CajitaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cBasic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnON)
                            .addComponent(rdbtnOFF)
                            .addComponent(rdbtnB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdbtnC)
                            .addComponent(rdbtnT)))
                    .addComponent(cCientific, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajitaTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajitaTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajitaTextoActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField CajitaTexto;
    public javax.swing.JLabel Etiquetita;
    public javax.swing.JButton btnAC;
    public javax.swing.JButton btnCos;
    public javax.swing.JButton btnCosh;
    public javax.swing.JButton btnDiv;
    public javax.swing.ButtonGroup btnGroupC;
    public javax.swing.ButtonGroup btnGroupO;
    public javax.swing.JButton btnInv;
    public javax.swing.JButton btnLog;
    public javax.swing.JButton btnLog10;
    public javax.swing.JButton btnMult;
    public javax.swing.JButton btnNum0;
    public javax.swing.JButton btnNum1;
    public javax.swing.JButton btnNum2;
    public javax.swing.JButton btnNum3;
    public javax.swing.JButton btnNum4;
    public javax.swing.JButton btnNum5;
    public javax.swing.JButton btnNum6;
    public javax.swing.JButton btnNum7;
    public javax.swing.JButton btnNum8;
    public javax.swing.JButton btnNum9;
    public javax.swing.JButton btnP2;
    public javax.swing.JButton btnP3;
    public javax.swing.JButton btnPY;
    public javax.swing.JButton btnPi;
    public javax.swing.JButton btnPorc;
    public javax.swing.JButton btnPuntito;
    public javax.swing.JButton btnR2;
    public javax.swing.JButton btnRes;
    public javax.swing.JButton btnResta;
    public javax.swing.JButton btnSin;
    public javax.swing.JButton btnSinh;
    public javax.swing.JButton btnSuma;
    public javax.swing.JButton btnTan;
    public javax.swing.JButton btnTanh;
    public javax.swing.JPanel cBasic;
    public javax.swing.JPanel cCientific;
    public javax.swing.JRadioButton rdbtnB;
    public javax.swing.JRadioButton rdbtnC;
    public javax.swing.JRadioButton rdbtnOFF;
    public javax.swing.JRadioButton rdbtnON;
    public javax.swing.JRadioButton rdbtnT;
    // End of variables declaration//GEN-END:variables

   
}
